#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

$autoloadPaths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../../../autoload.php',
];

foreach ($autoloadPaths as $autoloadPath) {
    if (file_exists($autoloadPath)) {
        require_once $autoloadPath;
        break;
    }
}

$application = new Application;
$application->addCommands([
        new PiPHP\PiPin\ExportCommand(),
        new PiPHP\PiPin\UnexportCommand(),
        new PiPHP\PiPin\ValueCommand(),
        new PiPHP\PiPin\DirectionCommand(),
        new PiPHP\PiPin\EdgeCommand(),
    ]);

$application->run();
