#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application;
$application->addCommands([
        new PiPHP\PiPin\ExportCommand(),
        new PiPHP\PiPin\UnexportCommand(),
        new PiPHP\PiPin\ValueCommand(),
        new PiPHP\PiPin\DirectionCommand(),
        new PiPHP\PiPin\EdgeCommand(),
    ]);

$application->run();
